# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'LoginForm' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'loginForm' do
    # Test name: Login_Form
    # Step # | name | target | value
    # 1 | open | /login | 
    @driver.get('https://app.jubelio.com/login')
    # 2 | setWindowSize | 691x711 | 
    @driver.manage.resize_to(691, 711)
    # 3 | type | name=email | qa.rakamin.jubelio@gmail.com
    @driver.find_element(:name, 'email').send_keys('qa.rakamin.jubelio@gmail.com')
    # 4 | click | name=password | 
    @driver.find_element(:name, 'password').click
    # 5 | type | name=password | Jubelio123!
    @driver.find_element(:name, 'password').send_keys('Jubelio123!')
    # 6 | assertTitle | Jubelio | 
    expect(@driver.title).to eq('Jubelio')
    # 7 | click | css=.ladda-button | 
    @driver.find_element(:css, '.ladda-button').click
  end
end
