# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'StokPersediaan' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'stokPersediaan' do
    # Test name: Stok Persediaan
    # Step # | name | target | value
    # 1 | open | /home/inventory | 
    @driver.get('https://app.jubelio.com/home/inventory')
    # 2 | setWindowSize | 691x711 | 
    @driver.manage.resize_to(691, 711)
    # 3 | click | css=.input-group > .form-control | 
    @driver.find_element(:css, '.input-group > .form-control').click
    # 4 | mouseOver | css=.btn-primary > .ladda-label | 
    element = @driver.find_element(:css, '.btn-primary > .ladda-label')
    @driver.action.move_to_element(element).perform
    # 5 | mouseOut | css=.btn-primary > .ladda-label | 
    element = @driver.find_element(By.CSS_SELECTOR, 'body')
    @driver.action.move_to_element(element, 0, 0).perform
    # 6 | type | css=.input-group > .form-control | asus
    @driver.find_element(:css, '.input-group > .form-control').send_keys('asus')
    # 7 | click | css=.glyphicon | 
    @driver.find_element(:css, '.glyphicon').click
    # 8 | click | id=select-all-checkbox | 
    @driver.find_element(:id, 'select-all-checkbox').click
    # 9 | click | id=list-children | 
    @driver.find_element(:id, 'list-children').click
    # 10 | click | linkText=SKU yang dipilih | 
    @driver.find_element(:link_text, 'SKU yang dipilih').click
    # 11 | click | css=.input-group > .form-control | 
    @driver.find_element(:css, '.input-group > .form-control').click
    # 12 | type | css=.input-group > .form-control | iphone 11
    @driver.find_element(:css, '.input-group > .form-control').send_keys('iphone 11')
    # 13 | click | css=.glyphicon-search | 
    @driver.find_element(:css, '.glyphicon-search').click
    # 14 | mouseOver | css=.ladda-button:nth-child(2) | 
    element = @driver.find_element(:css, '.ladda-button:nth-child(2)')
    @driver.action.move_to_element(element).perform
    # 15 | mouseOut | css=.ladda-button:nth-child(2) | 
    element = @driver.find_element(By.CSS_SELECTOR, 'body')
    @driver.action.move_to_element(element, 0, 0).perform
    # 16 | click | css=span .react-grid-checkbox-label | 
    @driver.find_element(:css, 'span .react-grid-checkbox-label').click
    # 17 | click | id=list-children | 
    @driver.find_element(:id, 'list-children').click
    # 18 | click | linkText=SKU yang dipilih | 
    @driver.find_element(:link_text, 'SKU yang dipilih').click
    # 19 | click | css=.input-group > .form-control | 
    @driver.find_element(:css, '.input-group > .form-control').click
    # 20 | type | css=.input-group > .form-control | iphone 
    @driver.find_element(:css, '.input-group > .form-control').send_keys('iphone ')
    # 21 | click | css=.glyphicon-search | 
    @driver.find_element(:css, '.glyphicon-search').click
    # 22 | mouseOver | css=.btn-primary > .ladda-label | 
    element = @driver.find_element(:css, '.btn-primary > .ladda-label')
    @driver.action.move_to_element(element).perform
    # 23 | mouseOut | css=.btn-primary > .ladda-label | 
    element = @driver.find_element(By.CSS_SELECTOR, 'body')
    @driver.action.move_to_element(element, 0, 0).perform
    # 24 | click | id=select-all-checkbox | 
    @driver.find_element(:id, 'select-all-checkbox').click
    # 25 | click | id=list-children | 
    @driver.find_element(:id, 'list-children').click
    # 26 | click | linkText=SKU yang dipilih | 
    @driver.find_element(:link_text, 'SKU yang dipilih').click
    # 27 | click | css=.input-group-btn > .btn-default | 
    @driver.find_element(:css, '.input-group-btn > .btn-default').click
    # 28 | click | css=.btn-info > .ladda-label | 
    @driver.find_element(:css, '.btn-info > .ladda-label').click
    # 29 | type | css=.form-group:nth-child(1) > .col-md-6 > .form-control | 1 Jun 2023
    @driver.find_element(:css, '.form-group:nth-child(1) > .col-md-6 > .form-control').send_keys('1 Jun 2023')
    # 30 | click | css=.react-fine-uploader-file-input | 
    @driver.find_element(:css, '.react-fine-uploader-file-input').click
  end
end
